# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lalo\PycharmProjects\ImageResizerUI\resizer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(463, 250)
        Dialog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.browse_btn = QtWidgets.QPushButton(Dialog)
        self.browse_btn.setGeometry(QtCore.QRect(370, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browse_btn.setFont(font)
        self.browse_btn.setObjectName("browse_btn")
        self.browse_text = QtWidgets.QLineEdit(Dialog)
        self.browse_text.setGeometry(QtCore.QRect(120, 30, 231, 21))
        self.browse_text.setObjectName("browse_text")
        self.browse_label = QtWidgets.QLabel(Dialog)
        self.browse_label.setGeometry(QtCore.QRect(20, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browse_label.setFont(font)
        self.browse_label.setObjectName("browse_label")
        self.resize_btn = QtWidgets.QPushButton(Dialog)
        self.resize_btn.setGeometry(QtCore.QRect(360, 210, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resize_btn.setFont(font)
        self.resize_btn.setObjectName("resize_btn")
        self.reset_btn = QtWidgets.QPushButton(Dialog)
        self.reset_btn.setGeometry(QtCore.QRect(260, 210, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reset_btn.setFont(font)
        self.reset_btn.setObjectName("reset_btn")
        self.width_text = QtWidgets.QLineEdit(Dialog)
        self.width_text.setGeometry(QtCore.QRect(90, 80, 61, 20))
        self.width_text.setObjectName("width_text")
        self.width_label = QtWidgets.QLabel(Dialog)
        self.width_label.setGeometry(QtCore.QRect(20, 80, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.width_label.setFont(font)
        self.width_label.setObjectName("width_label")
        self.height_text = QtWidgets.QLineEdit(Dialog)
        self.height_text.setGeometry(QtCore.QRect(90, 120, 61, 20))
        self.height_text.setObjectName("height_text")
        self.height_label = QtWidgets.QLabel(Dialog)
        self.height_label.setGeometry(QtCore.QRect(20, 120, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.height_label.setFont(font)
        self.height_label.setObjectName("height_label")
        self.px_label_width = QtWidgets.QLabel(Dialog)
        self.px_label_width.setGeometry(QtCore.QRect(160, 70, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.px_label_width.setFont(font)
        self.px_label_width.setObjectName("px_label_width")
        self.px_label_height = QtWidgets.QLabel(Dialog)
        self.px_label_height.setGeometry(QtCore.QRect(160, 110, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.px_label_height.setFont(font)
        self.px_label_height.setObjectName("px_label_height")
        self.aspect_ratio_checkbox = QtWidgets.QCheckBox(Dialog)
        self.aspect_ratio_checkbox.setGeometry(QtCore.QRect(210, 100, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aspect_ratio_checkbox.setFont(font)
        self.aspect_ratio_checkbox.setChecked(True)
        self.aspect_ratio_checkbox.setObjectName("aspect_ratio_checkbox")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(150, 80, 51, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(150, 120, 51, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(190, 90, 20, 40))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.resample_combobox = QtWidgets.QComboBox(Dialog)
        self.resample_combobox.setGeometry(QtCore.QRect(260, 160, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.resample_combobox.setFont(font)
        self.resample_combobox.setObjectName("resample_combobox")
        self.resample_combobox.addItem("")
        self.resample_combobox.addItem("")
        self.resample_combobox.addItem("")
        self.resample_combobox.addItem("")
        self.resample_combobox.addItem("")
        self.resample_combobox.addItem("")
        self.resample_combobox.addItem("")
        self.resample_combobox.addItem("")
        self.resample_label = QtWidgets.QLabel(Dialog)
        self.resample_label.setGeometry(QtCore.QRect(190, 160, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resample_label.setFont(font)
        self.resample_label.setObjectName("resample_label")
        self.resolution_label = QtWidgets.QLabel(Dialog)
        self.resolution_label.setGeometry(QtCore.QRect(20, 160, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resolution_label.setFont(font)
        self.resolution_label.setObjectName("resolution_label")
        self.resolution_text = QtWidgets.QLineEdit(Dialog)
        self.resolution_text.setGeometry(QtCore.QRect(90, 160, 61, 20))
        self.resolution_text.setObjectName("resolution_text")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Photoshop Bulk Image Resizer"))
        self.browse_btn.setText(_translate("Dialog", "Browse"))
        self.browse_label.setText(_translate("Dialog", "Browse Folder"))
        self.resize_btn.setText(_translate("Dialog", "Resize"))
        self.reset_btn.setText(_translate("Dialog", "Reset"))
        self.width_label.setText(_translate("Dialog", "Width"))
        self.height_label.setText(_translate("Dialog", "Height"))
        self.px_label_width.setText(_translate("Dialog", "px"))
        self.px_label_height.setText(_translate("Dialog", "px"))
        self.aspect_ratio_checkbox.setText(_translate("Dialog", "Maintain Aspect Ratio"))
        self.resample_combobox.setItemText(0, _translate("Dialog", "Automatic"))
        self.resample_combobox.setItemText(1, _translate("Dialog", "Preserve Details (Enlargement)"))
        self.resample_combobox.setItemText(2, _translate("Dialog", "Preserve Details (2.0)"))
        self.resample_combobox.setItemText(3, _translate("Dialog", "Bicubic Smoother (Enlargement)"))
        self.resample_combobox.setItemText(4, _translate("Dialog", "Bicubic Shaper (Reduction)"))
        self.resample_combobox.setItemText(5, _translate("Dialog", "Bicubic (Smooth Gradients)"))
        self.resample_combobox.setItemText(6, _translate("Dialog", "Nearest Neighbour (Hard Edges)"))
        self.resample_combobox.setItemText(7, _translate("Dialog", "Bi-linear"))
        self.resample_label.setText(_translate("Dialog", "Resample"))
        self.resolution_label.setText(_translate("Dialog", "Resolution"))
        self.resolution_text.setText(_translate("Dialog", "72"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

